# Generated by Django 2.0.1 on 2018-01-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0003_auto_20180128_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userhash',
            field=models.CharField(default='default_hash', max_length=128),
            preserve_default=False,
        ),
    ]
